"""Regenerate the frozen Unicode 15 case-fold table used by Python 3.12/3.13.

This is a developer-only tool. The released binary embeds the table and does
not call Python. Changing this table also changes Windows catalog state keys.
"""
from pathlib import Path
import unicodedata

if unicodedata.unidata_version not in {'15.0.0', '15.1.0'}:
    raise SystemExit('Use Python 3.12 or 3.13 to preserve the legacy Unicode 15 identity.')

rows = []
for number in range(0x110000):
    if 0xD800 <= number <= 0xDFFF:
        continue
    value = chr(number)
    folded = value.casefold()
    if value != folded:
        escaped = ''.join('\\u{' + format(ord(c), 'x') + '}' for c in folded)
        rows.append(f'    (0x{number:x}, "{escaped}"),')

output = Path(__file__).resolve().parents[1] / 'src/casefold_table.rs'
output.write_text('// Generated by scripts/generate_casefold.py; Unicode 15.0/15.1.\n'
                  '// Data terms: docs/licenses/UNICODE.txt. Do not update state-key semantics silently.\n'
                  'pub(super) static FOLDS: &[(u32, &str)] = &[\n' + '\n'.join(rows) + '\n];\n',
                  encoding='utf-8', newline='\n')
print(f'Wrote {len(rows)} case-fold mappings.')
